from seleniumbase import SB

with SB(uc=True, ad_block=True, test=True) as sb:
    sb.activate_cdp_mode()
    sb.goto("https://www.lesfurets.com/")
    sb.sleep(2)
    sb.click_if_visible("button#didomi-notice-agree-button", timeout=3)
    sb.sleep(1)
    sb.click('p:contains("Assurance moto")')
    sb.click('label[for="CYLINDREE_CYLINDREE_INF"]')
    sb.click('label[for="VEH_POSSESSION_false"]')
    sb.click('label[for="VEH_TYPE_ACQUISITION_premier"]')
    sb.click("button.userValidation")
    sb.click('div[data-testid="DATE_CIRCULATION_VEHICULE-month"]')
    sb.click('span:contains("Janvier")')
    sb.click('div[data-testid="DATE_CIRCULATION_VEHICULE-year"]')
    sb.click('div[data-value="2026"] span')
    sb.click('div[data-testid="ACHAT_PREVU_VEHICULE-month"]')
    sb.click('span:contains("Mars")')
    sb.click('div[data-testid="ACHAT_PREVU_VEHICULE-year"]')
    sb.click('div[data-value="2027"] span')
    sb.click('div[data-testid="PERMIS"]')
    sb.click('span:contains("Aucun")')
    sb.click("button.DaisyBlockView-next")
    sb.assert_element("div.VehiculePickerField")
    sb.click('label:contains("Choisir votre véhicule")')
    sb.type("input#modele_picker", "2TWENTY")
    sb.sleep(3)
